site_name: Plateforme de Gestion des PFA — Project #47
site_url: https://Malek720.github.io/PFA_PROJECT/
theme:
  name: material
  palette:
    primary: indigo
    accent: teal
docs_dir: docs
use_directory_urls: false

nav:
  - Home: index.md
  - Cahier des Charges:
    - Contexte: Cahier_des_charges/Contexte.md
    - Acteurs: Cahier_des_charges/Acteurs.md
    - Besoins fonctionnels: Cahier_des_charges/Besoins fonctionnels.md
    - Besoins non fonctionnels: Cahier_des_charges/Besoins non fonctionnels.md
  - UML Diagrams:
    - Cas d'utilisation: Diagrammes_UML/Cas d'utilisation.md
    - Diagramme de classes: Diagrammes_UML/Diagramme de classes.md
    - Séquence — Candidature: Diagrammes_UML/Séquence — Candidature.md
  - Architecture:
    - Stack technique: Architecture/Stack technique.md
  - Suivi de stage:
    - Journal hebdomadaire: Suivi_de_stage/Journal hebdomadaire.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js